# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c6842d07ce5ec5a9ad07e596e5304b7ec57b23fcc826b6eb998728620996f4802a39a6d300b19233bad434b55c374e8ae2fad053d7ea820e19da399e3477b25

test:
  secret_key_base: 58c2808db839ecd2de7ba19b31d79e26602736bff418e8fd0e357c6621874eeef68019b6c8f89fa94f3c17802abba6ad2460dd810741d126cb979f9dd4b26373

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
